/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...miss]': RouteRecordInfo<'/[...miss]', '/:miss(.*)', { miss: ParamValue<true> }, { miss: ParamValue<false> }>,
    '/password-strength-analyser': RouteRecordInfo<'/password-strength-analyser', '/password-strength-analyser', Record<never, never>, Record<never, never>>,
    '/token-generator': RouteRecordInfo<'/token-generator', '/token-generator', Record<never, never>, Record<never, never>>,
  }
}
